### ISSUE TITLE
Content appears to be duplicated in kernelspec

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlite/echo-kernel#5]
Spotted by @johanmabille.

We see that the content of the `spec` is mostly repeated with little variation here: https://github.com/jupyterlite/echo-kernel/blob/5f28f3a40684b72be12925eb7e26d4c81bb4d04c/src/index.ts#L22-L38

**Comment by jtpio** [comment]
Thanks for reporting :+1: 

There seems to be a discrepancy between the `KernelSpec.ISpecModel` type used to register the spec here, and the type returned from the `/api/kernelspecs` endpoint in JupyterLite.

Will look into this.
